DROP TABLE IF EXISTS `streamfix`.`users`;
CREATE TABLE `streamfix`.`users`
(
    USER_ID     VARCHAR(255) NOT NULL COMMENT '사용자 ID (UUID)',
    USER_NAME   VARCHAR(50)  NOT NULL COMMENT '사용자 이름',
    PASSWORD    VARCHAR(255) NOT NULL COMMENT '사용자 비밀번호 (암호화)',
    EMAIL       VARCHAR(255) NOT NULL COMMENT '이메일',
    PHONE       VARCHAR(255) NOT NULL COMMENT '전화번호',

    CREATED_AT  DATETIME     NOT NULL COMMENT '생성일자',
    CREATED_BY  VARCHAR(50)  NOT NULL COMMENT '생성자',
    MODIFIED_AT DATETIME     NOT NULL COMMENT '수정일자',
    MODIFIED_BY VARCHAR(50)  NOT NULL COMMENT '수정자',

    PRIMARY KEY (USER_ID)
);

DROP TABLE IF EXISTS `streamfix`.`sample`;
CREATE TABLE `streamfix`.`sample`
(
    SAMPLE_ID   VARCHAR(255) NOT NULL,
    SAMPLE_NAME VARCHAR(50)  NOT NULL,
    SAMPLE_DESC VARCHAR(255) NOT NULL,

    PRIMARY KEY (SAMPLE_ID)
);