spring:
  config:
    import:
      - 'classpath:adapter-http-property.yml'
      - 'classpath:adapter-persistence.property.yml'
      - 'classpath:adapter-redis.property.yml'
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy}
            scope: openid,profile,email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

server:
  port: 8080

logging:
  level:
    com.shokoku.streamfix: DEBUG
